"""
Configuration loader — reads all settings from .env with validation.
This is the single source of truth for all configuration values.
"""

from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path
from typing import Annotated

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Config(BaseSettings):
    """All bot configuration, loaded from .env with validation."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # ── Wallet (never log these) ──────────────────────────────────────────────
    private_key: str = Field(default="", description="Polygon private key — NEVER LOG")
    funder_address: str = Field(default="", description="Polymarket deposit address")
    signature_type: int = Field(default=0, description="0=EOA, 1=Magic/Email")

    # ── Polymarket CLOB API credentials (generated by setup_wallet.py) ───────
    # L2 credentials are required for authenticated endpoints in live trading.
    # Run: python scripts/setup_wallet.py  to generate and save these.
    clob_api_key: str = Field(default="", description="Polymarket CLOB API key — NEVER LOG")
    clob_secret: str = Field(default="", description="Polymarket CLOB API secret — NEVER LOG")
    clob_pass_phrase: str = Field(default="", description="Polymarket CLOB passphrase — NEVER LOG")

    def has_clob_creds(self) -> bool:
        """Returns True if L2 CLOB API credentials are configured."""
        return bool(self.clob_api_key and self.clob_secret and self.clob_pass_phrase)

    # ── Polymarket endpoints ──────────────────────────────────────────────────
    polymarket_clob_url: str = "https://clob.polymarket.com"
    polymarket_ws_url: str = "wss://ws-subscriptions-clob.polymarket.com/ws/market"
    polymarket_gamma_url: str = "https://gamma-api.polymarket.com"
    polygon_chain_id: int = 137
    polygon_rpc_url: str = "https://polygon-rpc.com"

    # ── Market data endpoints ─────────────────────────────────────────────────
    binance_ws_url: str = "wss://stream.binance.com:9443/ws/btcusdt@trade"
    binance_eth_ws_url: str = "wss://stream.binance.com:9443/ws/ethusdt@trade"
    binance_rest_url: str = "https://api.binance.com"
    chainlink_btc_usd_proxy: str = "0xc907E116054Ad103354f2D350FD2514433D57F6f"
    chainlink_eth_usd_proxy: str = "0xF9680D99D6C9589e2a93a78A04A279e509205945"

    # ── Strategy parameters ───────────────────────────────────────────────────
    trade_amount_usd: float = Field(default=20.0, ge=1.0, le=1000.0)
    max_trade_amount_usd: float = Field(default=1000.0, ge=1.0, le=10000.0)
    # Lowered from 51: allow trades down to 42% confidence.
    # Kelly criterion still prevents negative-EV trades — this just lets more
    # signals through so the executor can evaluate them.
    min_confidence_score: int = Field(default=60, ge=0, le=100)
    min_token_price: float = Field(default=0.30, ge=0.01, le=0.99)
    max_token_price: float = Field(default=0.88, ge=0.01, le=0.99)
    # Enter at T+5s (295s remaining) — before market makers reprice from 0.50 to 0.99.
    # By T+80s (old default) the direction is already priced at 99%.
    entry_window_start_sec: int = Field(default=270, ge=5, le=299)
    trading_window_start_sec: int = Field(default=240, ge=5, le=298)
    entry_deadline_sec: int = Field(default=90, ge=1, le=120)
    max_concurrent_positions: int = Field(default=2, ge=1, le=10)
    # Minimum BTC delta (% from window open) required to consider trading.
    # Very low (0.005%) allows early-window signals where BTC barely moved yet.
    min_window_delta_pct: float = Field(default=0.005, ge=0.001, le=0.5)
    # No minimum edge floor — Kelly criterion in position sizer handles edge protection.
    min_trade_edge: float = Field(default=0.0, ge=0.0, le=0.15)

    # Seconds remaining in window below which we switch from GTC maker to FOK taker.
    # Above this threshold we bid at fair value via a resting limit order.
    # Below it, the window is too short to wait for a maker fill — use FOK.
    gtc_window_sec: int = Field(default=120, ge=5, le=280)

    # ── Risk management ───────────────────────────────────────────────────────
    max_daily_loss_usd: float = Field(default=300.0, ge=1.0)
    max_drawdown_pct: float = Field(default=25.0, ge=1.0, le=100.0)
    max_consecutive_losses: int = Field(default=5, ge=1, le=20)
    kelly_fraction: float = Field(default=0.25, ge=0.01, le=1.0)
    min_usdc_balance: float = Field(default=50.0, ge=1.0)

    # ── Paper trading ─────────────────────────────────────────────────────────
    paper_mode: bool = True
    paper_initial_balance: float = Field(default=1000.0, ge=100.0)

    # ── Dashboard / WebSocket ─────────────────────────────────────────────────
    ws_server_port: int = Field(default=8765, ge=1024, le=65535)
    dashboard_port: int = Field(default=3000, ge=1024, le=65535)

    # ── Logging ───────────────────────────────────────────────────────────────
    log_level: str = Field(default="INFO")
    log_file: str = "logs/polyoracle.log"

    # ── Derived constants (not from env) ─────────────────────────────────────
    window_duration_sec: int = 300          # 5-minute windows
    min_trade_shares: float = 5.0           # Polymarket minimum order size
    max_position_pct: float = 0.08          # Never bet more than 10% of balance
    kelly_accuracy_window: int = 50         # Rolling window for meta-learner
    agent_mute_threshold: float = 0.45      # Mute agents below 45% accuracy

    @field_validator("log_level")
    @classmethod
    def validate_log_level(cls, v: str) -> str:
        valid = {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}
        if v.upper() not in valid:
            raise ValueError(f"log_level must be one of {valid}")
        return v.upper()

    @field_validator("min_token_price", "max_token_price")
    @classmethod
    def validate_token_price_range(cls, v: float) -> float:
        return round(v, 4)

    def is_live(self) -> bool:
        """Returns True if running in live (non-paper) mode."""
        return not self.paper_mode

    def has_wallet(self) -> bool:
        """Returns True if a valid private key is configured."""
        key = self.private_key.strip()
        if not key:
            return False
        # Accept with or without 0x prefix — MetaMask exports without it
        raw = key[2:] if key.startswith("0x") else key
        return len(raw) == 64 and all(c in "0123456789abcdefABCDEF" for c in raw)

    @property
    def normalized_private_key(self) -> str:
        """Always returns the private key with 0x prefix."""
        key = self.private_key.strip()
        return key if key.startswith("0x") else f"0x{key}"

    def __repr__(self) -> str:
        # Never include private_key or API credentials in repr
        return (
            f"Config(paper_mode={self.paper_mode}, "
            f"trade_amount=${self.trade_amount_usd}, "
            f"min_confidence={self.min_confidence_score}, "
            f"has_wallet={self.has_wallet()}, "
            f"has_clob_creds={self.has_clob_creds()})"
        )


@lru_cache(maxsize=1)
def get_config() -> Config:
    """Return the singleton Config instance (cached after first load)."""
    return Config()


# ── Module-level convenience alias ────────────────────────────────────────────
# Usage: from core.config import cfg
cfg = get_config()
